### ISSUE TITLE
Add Kent Rancourt (krancour) as a core maintainer on brigadecore/brigade

### ISSUE THREAD

**Issue by technosophos** [brigadecore/community#12]
This issue formally invites the maintainers to vote on adding @krancour as a core maintainer on the brigadecore/brigade project. Kent has been the principal driver for all of the Brigade Next planning work, and is currently writing the proposal for Brigade 2.0. Having him as a core maintainer is a critical part of the plan to make Brigade 2 a reality.

We do not have a formally defined method of voting in new candidates but the guidelines require that we have a supermajority vote. The current list of eligible voters are: @technosophos @adamreese @mumoshu @vdice @radu-matei @lukepatrick

The vote will be opened until June 1, 2020 or until at least 4 core maintainers approve. I would like to suggest that as an additional stipulation, at least one such person must not be from Microsoft. Therefore, I will not cast my vote until after one non-MS person has voted.

**Comment by technosophos** [comment]
To vote, simply add a +1 comment or statement on this issue.

**Comment by vdice** [comment]
I hereby cast my ballot as a vote of recommendation for adding Kent Rancourt as a core maintainer to Brigade! 👍 

(Assuming consensus will be reached here in this issue, we can use https://github.com/brigadecore/brigade/pull/1081 as the PR to add Kent to the CODEOWNERS file)

**Comment by radu-matei** [comment]
+1

**Comment by technosophos** [comment]
Sorry, I didn't see the one in Brigade. I only thought to look here. My bad. I see that @lukepatrick also voted there. 🤦 Sorry for the inconvenience.

**Comment by lukepatrick** [comment]
+1

**Comment by technosophos** [comment]
+1

**Comment by vdice** [comment]
CODEOWNERS list updated in https://github.com/brigadecore/brigade/pull/1081 ; closing.  🎉 👏
