### ISSUE TITLE
Refresh Brigade logo

### ISSUE THREAD

**Issue by flynnduism** [brigadecore/community#16]
With [Brigade 2.0](https://github.com/brigadecore/brigade/tree/v2) getting closer, I want to propose an update to the logo for the project. I created the current Brigade logo back in 2017 and would love to see it evolve in step with the project.

<img width="368" alt="Screen Shot 2021-06-04 at 7 18 22 PM" src="https://user-images.githubusercontent.com/686194/120877141-a840f780-c569-11eb-939e-68cd5b0b4eba.png">

## Logo issues

* The logo was intended to mirror [Helm](https://helm.sh/), but it's too large and busy to have have the same simple impact
* Uppercase logo is a bit _shouty_
* Colors are pretty faded, low contrast = low legibility
* Doesn't scale down well for icons/avatars

---

## Redesign

Ideally the logo should embody a bit about what Brigade does. The Kubernetes focus of the wheel is less critical now that the project is a bit more established, so I think it makes sense to bring in some of the symbolism around events, pipelines, scripting and CICD tooling.

<img width="696" alt="Screen Shot 2021-06-04 at 7 22 33 PM" src="https://user-images.githubusercontent.com/686194/120877241-5056c080-c56a-11eb-9c11-3106fd5da030.png">

<img width="414" alt="Screen Shot 2021-06-04 at 3 30 42 PM" src="https://user-images.githubusercontent.com/686194/120877247-551b7480-c56a-11eb-88c8-16fb89679f29.png">

---

## 2.0 Theme Ideas

I think a set of bolder colors, and imagery around sequences of events / jobs (like a flowchart or a workflow pipeline) could make for a nice playful brand theme.

![01-Brigade-Moodboard-02](https://user-images.githubusercontent.com/686194/120877312-b4798480-c56a-11eb-8035-731963de934f.jpg)

For typography, I really like Work Sans that the project currently uses - and would like to introduce a chunkier, rounder typeface for headlines.

![03-Brigade-Typography](https://user-images.githubusercontent.com/686194/120877314-bc392900-c56a-11eb-974e-475b5a7abffc.png)

Color ideas.

![02-Brigade-Theme](https://user-images.githubusercontent.com/686194/120877318-c1967380-c56a-11eb-9a19-53f7e4619a9f.png)

## Logo Ideas

![04-Brigade-Icon-Dev](https://user-images.githubusercontent.com/686194/120877421-41244280-c56b-11eb-842c-9a03f01a74ac.png)

^ First bunch of ideas.

<img width="1069" alt="Screen Shot 2021-06-04 at 7 27 08 PM" src="https://user-images.githubusercontent.com/686194/120877436-5600d600-c56b-11eb-820d-c3dccb4a2bbc.png">

 

^ Second bunch of ideas.

Changing out the dots + paths aspect of the logo to try and show more detail around a series of jobs / tasks. 

## Proposed Logo

Ultimately this is what I'd like to propose as a new Brigade logo. I've a couple of ideas for condensing the logo to a smaller icon in certain settings, which are shown on the right hand side:

<img width="820" alt="Screen Shot 2021-06-04 at 4 09 33 PM" src="https://user-images.githubusercontent.com/686194/120877610-5352b080-c56c-11eb-8c38-073a4dfae385.png">

**Comment by krancour** [comment]
I absolutely love this.

@vdice @radu-matei @technosophos any opinions?

**Comment by radu-matei** [comment]
This is amazing, I love it!
Everything is great, the brand theme, typography, and especially the proposed logo.

**Comment by carolynvs** [comment]
Looks great!

**Comment by technosophos** [comment]
The wordmark is so awesome. I love the way you worked the dotted line, the i, and the curve of the B together.

Yeah, I love these.

**Comment by vdice** [comment]
Yup, totally in support of this.  Awesome work (as always), @flynnduism!

**Comment by krancour** [comment]
Closed by #17
