### ISSUE TITLE
Add Karen Chu (@karenhchu) as a project maintainer on brigadecore/community

### ISSUE THREAD

**Issue by krancour** [brigadecore/community#21]
This issue formally invites existing maintainers to vote on adding Karen Chu (@karenhchu) as a maintainer _specifically_ on the brigadecore/community project.

There is a distinction already drawn between the project maintainer and org maintainer roles ([defined here](https://github.com/brigadecore/community/blob/main/governance.md)), although Brigade hasn't actually observed any practical difference between those two roles until now.

Karen is a Microsoft PM who is playing a pivotal role in efforts to build/rebuild the Brigade community. Giving her the maintainer role for the brigadecore/community project would both recognize her efforts and streamline maintenance of the community repository. It would also grant her further latitude WRT CNCF to act as an agent on behalf of Brigade.

If her nomination is ratified, she would be added to the [community-maintainers](https://github.com/orgs/brigadecore/teams/community-maintainers) group in this org. That group is already listed as a CODEOWNER for this repository.

We do not have a formally defined method of voting in new candidates but the guidelines require that we have a supermajority vote. The current list of eligible voters are: @technosophos @adamreese @mumoshu @vdice @radu-matei @lukepatrick @krancour.

The vote will be opened until Oct 15, 2021 or until at least 4 existing maintainers approve.

To vote, simply add a +1 comment or statement on this issue.

**Comment by radu-matei** [comment]
❤️ 
+1

**Comment by krancour** [comment]
And of course I am in favor.

+1

**Comment by vdice** [comment]
+1 ❗

**Comment by technosophos** [comment]
+1

**Comment by krancour** [comment]
The motion carries!
