### ISSUE TITLE
Add Ronan Flynn-Curran (@flynnduism) as a project maintainer on brigadecore/community

### ISSUE THREAD

**Issue by krancour** [brigadecore/community#22]
This issue formally invites existing maintainers to vote on adding Ronan Flynn-Curran (@flynnduism) as a maintainer _specifically_ on the brigadecore/community project.

Ronan has already been acting in the capacity of repo maintainer for brigadecore/community for some time, so this issue is a matter of formality.

If his nomination is ratified, he would be added to the [community-maintainers](https://github.com/orgs/brigadecore/teams/community-maintainers) group in this org. That group is already listed as a CODEOWNER for this repository.

We do not have a formally defined method of voting in new candidates but the guidelines require that we have a majority vote. The current list of eligible voters include org maintainers: @technosophos @adamreese @mumoshu @vdice @radu-matei @lukepatrick @krancour and repo maintainer @karenhchu.

The vote will be opened until Oct 26, 2021 or until at least 5 voters approve.

To vote, simply add a +1 comment or statement on this issue.

**Comment by karenhchu** [comment]
+1 !!!
