### ISSUE TITLE
Verify Brigade domain

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/community#6]
Do we want to verify our domain name for the GitHub organization?

Not sure if there are best practices / recommendations from CNCF on this - cc @caniszczyk 

![DEA8700C-3596-4737-BBB6-3923E8301961](https://user-images.githubusercontent.com/13103165/58312081-db910d80-7e0a-11e9-9928-79413f1cf578.jpeg)

**Comment by krancour** [comment]
Closing due to staleness.

**Comment by radu-matei** [comment]
This is still something we should do though.

**Comment by caniszczyk** [comment]
FYI this is verified now

**Comment by krancour** [comment]
@caniszczyk awesome. Thanks!

**Comment by radu-matei** [comment]
Thanks a lot, Chris!
