### ISSUE TITLE
List of externally-maintained components / dependencies

### ISSUE THREAD

**Issue by radu-matei** [brigadecore/community#9]
Possibly link to the [FOSSA dashboard](https://app.fossa.io/projects/git%2Bgithub.com%2Fbrigadecore%2Fbrigade?ref=badge_large).

[CII Best practices](https://bestpractices.coreinfrastructure.org/en/projects/2688?criteria_level=1).

**Comment by krancour** [comment]
Closing due to staleness. Please do reopen if necessary.
